---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-nat-vpp
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: node01
      containers:
        - name: nse
          env:
            - name: NSM_SERVICE_NAME
              value: "nse-composition"
            - name: NSM_LABELS
              value: app:nat
